//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System.Drawing;
using System.Windows.Forms;

namespace UlteriusServer.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("UlteriusServer.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Icon similar to (Icon).
        /// </summary>
        internal static Icon ApplicationIcon {
            get {
                object obj = ResourceManager.GetObject("ApplicationIcon", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to If authorized, Ulterius can collect data on its performance, feature usage, and configuration, as well as data on your system&apos;s hardware, network and operating system.
        ///
        /// No private data is ever collected. This data helps us understand how people and companies use Ulterius and prioritize our efforts. It also helps us identify rare configurations that are causing bugs, performance and stability issues.
        ///This authorization can be revoked at any time through Ulterius&apos;s settings.
        ///
        ///Do you authorize Ulterius t [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string HardwareSurvey_Setup_ {
            get {
                return ResourceManager.GetString("HardwareSurvey_Setup_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Usage statistics reporting.
        /// </summary>
        internal static string HardwareSurvey_Setup_Usage_statistics_reporting {
            get {
                return ResourceManager.GetString("HardwareSurvey_Setup_Usage_statistics_reporting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Its recommended You need to elevate this server to administrator..
        /// </summary>
        internal static string Program_Main_Its_recommended_You_need_to_elevate_this_server_to_administrator_ {
            get {
                return ResourceManager.GetString("Program_Main_Its_recommended_You_need_to_elevate_this_server_to_administrator_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Settings didn&apos;t exist, writing to disk..
        /// </summary>
        internal static string Program_Main_Settings_didn_t_exist__writing_to_disk_ {
            get {
                return ResourceManager.GetString("Program_Main_Settings_didn_t_exist__writing_to_disk_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Starting Task Api On .
        /// </summary>
        internal static string Program_Main_Starting_TaskServer_on_ {
            get {
                return ResourceManager.GetString("Program_Main_Starting_TaskServer_on_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Web Server is running on this port: .
        /// </summary>
        internal static string Program_Main_Web_Server_is_running_on_this_port__ {
            get {
                return ResourceManager.GetString("Program_Main_Web_Server_is_running_on_this_port__", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ulterius Server.
        /// </summary>
        internal static string Program_Title {
            get {
                return ResourceManager.GetString("Program_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string Settings {
            get {
                return ResourceManager.GetString("Settings", resourceCulture);
            }
        }
    }
}
