//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System.CodeDom.Compiler;
using System.ComponentModel;
using System.Diagnostics;
using System.Diagnostics.CodeAnalysis;
using System.Drawing;
using System.Globalization;
using System.Resources;
using System.Runtime.CompilerServices;

namespace UlteriusServer.Properties {
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [GeneratedCode("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [DebuggerNonUserCode()]
    [CompilerGenerated()]
    internal class Resources {
        
        private static ResourceManager resourceMan;
        
        private static CultureInfo resourceCulture;
        
        [SuppressMessage("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [EditorBrowsable(EditorBrowsableState.Advanced)]
        internal static ResourceManager ResourceManager {
            get {
                if (ReferenceEquals(resourceMan, null)) {
                    ResourceManager temp = new ResourceManager("UlteriusServer.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [EditorBrowsable(EditorBrowsableState.Advanced)]
        internal static CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Icon similar to (Icon).
        /// </summary>
        internal static Icon icon {
            get {
                object obj = ResourceManager.GetObject("icon", resourceCulture);
                return ((Icon)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Its recommended You need to elevate this server to administrator..
        /// </summary>
        internal static string Program_Main_Its_recommended_You_need_to_elevate_this_server_to_administrator_ {
            get {
                return ResourceManager.GetString("Program_Main_Its_recommended_You_need_to_elevate_this_server_to_administrator_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Settings didn&apos;t exist, writing to disk..
        /// </summary>
        internal static string Program_Main_Settings_didn_t_exist__writing_to_disk_ {
            get {
                return ResourceManager.GetString("Program_Main_Settings_didn_t_exist__writing_to_disk_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Starting TaskTServer on .
        /// </summary>
        internal static string Program_Main_Starting_TaskServer_on_ {
            get {
                return ResourceManager.GetString("Program_Main_Starting_TaskServer_on_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Web TServer is running on this port: .
        /// </summary>
        internal static string Program_Main_Web_Server_is_running_on_this_port__ {
            get {
                return ResourceManager.GetString("Program_Main_Web_Server_is_running_on_this_port__", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ulterius Task Manager.
        /// </summary>
        internal static string Program_Title {
            get {
                return ResourceManager.GetString("Program_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string Settings {
            get {
                return ResourceManager.GetString("Settings", resourceCulture);
            }
        }
    }
}
